development:
  adapter: sqlserver
  host: 192.168.1.19
  port: 1433
  database: wlg0801
  username: sa
  password: xlht

bq:
  adapter: sqlserver
  host: 192.168.1.19
  port: 1433
  database: bq
  username: sa
  password: xlht

wlg0801:
  adapter: sqlserver
  host: 192.168.1.19
  port: 1433
  database: wlg0801
  username: sa
  password: xlht

test:
  adapter: sqlserver
  host: 192.168.1.19
  port: 1433
  database: sms_test
  username: sa
  password: xlht

production:
  adapter: sqlserver
  host: 192.168.0.18
  port: 1433
  database: sms_test
  username: sa
  password: '123456'
